name: Go Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Adjust this version as needed

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest

      - name: Go mod tidy
        run: go mod tidy

      - name: Run tests
        run: make test
        env:
          GO: go
          GOROOT: ${{ env.GOROOT }}
          DEBUG_I2P: debug
          CGO_ENABLED: 0
      - name: Run all test suites
        run: make test-all
        env:
          GO: go
          GOROOT: ${{ env.GOROOT }}
          DEBUG_I2P: debug
          CGO_ENABLED: 0